INSERT  INTO
	lh_ds_ask
      ( 
      ID                            
      ,ASK_TITLE                      
      ,DESCRIPTION                    
      ,CATEGORY_ID                    
      ,ASK_URL                        
      ,TRANS_ASK_URL                  
      ,ANSWER_URL                     
      ,TRANS_ANSWER_URL               
      ,ASK_NUM                        
      ,ASK_STATUS                     
      ,ASK_PERSON_ID                  
      ,ASK_OPEN_ID                    
      ,ASK_DATE                       
      ,DEAL_PERSON_ID                 
      ,DEAL_OPEN_ID                   
      ,DEAL_DATE         
      ,ANSWER_OPEN_ID
      ,AUDIT                          
      ,REPLY                          
      ,PROCESSINSTANCEID              
      ,REMARK                         
      ,FORM_ID               
      ,black
      ) 
values
      (
      :lhDsAsk.id                            
      ,:lhDsAsk.askTitle                      
      ,:lhDsAsk.description                   
      ,:lhDsAsk.categoryId                    
      ,:lhDsAsk.askUrl                        
      ,:lhDsAsk.transAskUrl                   
      ,:lhDsAsk.answerUrl                     
      ,:lhDsAsk.transAnswerUrl                
      ,:lhDsAsk.askNum                        
      ,:lhDsAsk.askStatus                     
      ,:lhDsAsk.askPersonId                   
      ,:lhDsAsk.askOpenId                     
      ,:lhDsAsk.askDate                       
      ,:lhDsAsk.dealPersonId                  
      ,:lhDsAsk.dealOpenId                    
      ,:lhDsAsk.dealDate                      
      ,:lhDsAsk.answerOpenId                    
      ,:lhDsAsk.audit                         
      ,:lhDsAsk.reply                         
      ,:lhDsAsk.processinstanceid             
      ,:lhDsAsk.remark                        
      ,:lhDsAsk.formId                        
      ,:lhDsAsk.black  
      )